### ISSUE TITLE
Specify supported engines

### ISSUE THREAD

**Issue by merlinnot** [processout/processout-node#7]
`package.json` file does not contain an [engines field](https://docs.npmjs.com/files/package.json#engines), so there's no indication to the required version of Node.js and it's impossible to determine which optimizations/refactoring should be applied, as it heavily depends on available ECMAScript features.

An expectation would be to define this field, preferably with Node.js 10 as a minimal version, as Node.js 8 reached EOL on December 31st.

**Comment by manuel-huez** [comment]
We aim at maximal support for our SDKs with the highest possible backward compatibility for our merchants. Some of them are still using Node 8, so I'd rather not drop support for it yet (even if I do agree that it'd be a good next step considering its passed EOL).

That being said, I'm definitely not an expert in NPM; perhaps there are some other ways to enable optimizations without limiting the node versions?

**Comment by merlinnot** [comment]
We could also specify Node.js 8, if you still want to support it. There are no immediate effects of setting it in `package.json` other than users being informed about the incompatibility when they install it on older versions. It doesn't impact the runtime in any way.

This alignment, documented in that way, allows me to make further recommendations. As an example, a target of the TypeScript compiler, which results in generation of a more modern (smaller and better optimized) code: https://github.com/processout/processout-node/blob/eb019fe5544eee1b8ef1492b5811eb25ea0a1c12/tsconfig.json#L4.

**Comment by merlinnot** [comment]
Resolved by 6d9f114f56ecd9621d1fd1bb1789c7b0cc183974.
